### ISSUE TITLE
Suggestion: Avoid using inline styling unless necessary.

### ISSUE THREAD

**Issue by josephtkim** [Brosof8/prj-rev-bwfs-dasmoto#3]
For the sake of more efficient and cleaner code, it is best to keep HTML and CSS code separate. Instead of using inline styling for the pricing sections, you can add a class to each tag containing the text, and apply styling in the CSS code. Also, consider using span tags instead, because they apply no default styling to the text. For instance

HTML:
```html
<span class="pricing">Starting at $3.00/brush.</span>
```

CSS:
```css
.pricing {
  font-family:Helvetica;
  font-weight:bold;
  color:blue;
}
```
