### ISSUE TITLE
Simplify CSS code for shared properties. 

### ISSUE THREAD

**Issue by josephtkim** [Brosof8/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. To simplify the code, you can apply shared properties to multiple selectors at once, rather than applying them to each selector individually. For example, here is how your code might be simplified

```css
#heading {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  color: khaki;
  font-size: 100px;
  text-align: center;
}

#heading, h2 {
  font-family: Helvetica;
  font-weight: bold;
}

h2 {
  font-size: 32px;
  color: white;
}

#brushes-text {
  background-color: mediumspringgreen;
}

#frames-text {
  background-color: lightcoral;
}

#paint-text {
  background-color: skyblue;
}
```
